### ISSUE TITLE
Fake data CI integration

### ISSUE THREAD

**Issue by vinceAmstoutz** [makinacorpus/DbToolsBundle#109]
Just a quick question as to whether or not it's good practice to store an anonymized snapshot generated with DbToolsBundle, on a private GitHub repo, and use it for devs or unit testing a GitHb actions pipeline for example, instead of using fake data (using Foundry for example)?

**Comment by SimonMellerin** [comment]
I have no strong opinion on this. But, I would say that if you do that, 

1. you have to be sure about your anonymization configuration (no sensitive data should remain)
2. you should probably be concerned about the size of your backup. If it's too big, is probably not a good idea

I think it could be a good idea if your backup represents only a small part of your snapshot: enough to have real good data to develop and to perform functional tests, but no too much to keep it small.

**Comment by vinceAmstoutz** [comment]
Ok I will test this in a la. Thanks
